# OWNER IDENTITY (FIXED)
OWNER_PHONE = "9679299040"
OWNER_EMAIL = "sroy9679299040@gmail.com"

# PASSWORD (CHANGE IT)
OWNER_PASSWORD = "CHANGE_ME"

# EMAIL SMTP (Gmail example)
SMTP_SERVER = "smtp.gmail.com"
SMTP_PORT = 587
SMTP_EMAIL = "sroy9679299040@gmail.com"
SMTP_PASSWORD = "cgwtcqsezbyncajz"

# ANTI-HACK
FAILED_LIMIT = 5
AUTO_UNLOCK_SECONDS = 300  # 10 min

ALERT_EMAILS = [
    OWNER_EMAIL
]
